import Head from "next/head"
import Image from "next/image"

export default function Login() {
    return (
        <div>
            <Head>
                <title>Next Auth Tutorial</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main>
                <h2 className="text-2xl font-bold dark:text-gray-50">Login Page</h2>
            </main>
        </div>
    )
}
