import Head from "next/head"
import { app } from "@/firebase/config"
import { useState, createUserWithEmailAndPassword } from "react"
import { getAuth } from "firebase/auth"

export default function Register() {
    const auth = getAuth()
    const [email, setEmail] = useState("")
    const [password, setPassword] = useState("")

    const signUp = () => {
        createUserWithEmailAndPassword(auth, email, password).then(() => {})
    }
    return (
        <div>
            <Head>
                <title>Next Auth Tutorial</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className="text-center dark:bg-gray-700 p-4">
                <h2 className="text-2xl font-bold p-4">Register Page</h2>
                <div className="flex justify-center">
                    <div className="flex flex-col w-72 items-end gap-6">
                        <input
                            className="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500"
                            placeholder="email"
                            onChange={(e) => setEmail(e.target.value)}
                            value={email}
                        />
                        <input
                            className="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500"
                            placeholder="password"
                            onChange={(e) => setPassword(e.target.value)}
                            value={password}
                        />
                    </div>
                </div>
            </main>
        </div>
    )
}
